routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Application\csv\InvoiceController;

// Landing
Route::get('/', 'HomeController@index')->middleware('installed')->name('home');
// Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

// Route::get('/register', 'RegisterController@index')->name('register');



// Google Login


Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');


// Auth routes
// Auth::routes(['verify' => true]);
 Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// PDF Views
Route::get('/viewer/invoice/{invoice}/pdf', 'Application\PDFController@invoice')->name('pdf.invoice');
Route::get('/viewer/estimate/{estimate}/pdf', 'Application\PDFController@estimate')->name('pdf.estimate');
Route::get('/viewer/payment/{payment}/pdf', 'Application\PDFController@payment')->name('pdf.payment');

// Webhooks
Route::post('/order/checkout/{plan}/mollie/webhook', 'Application\OrderController@mollie_webhook')->name('order.payment.mollie.webhook');

// Super Admin Panel
Route::group(['namespace' => 'SuperAdmin', 'prefix' => '/admin', 'middleware' => [ 'auth', 'super_admin']], function () {
    // Dashboard
    Route::get('/dashboard', 'DashboardController@index')->name('super_admin.dashboard');

    // Users
    Route::get('/users', 'UserController@index')->name('super_admin.users');
    Route::get('/users/create', 'UserController@create')->name('super_admin.users.create');
    Route::post('/users/store', 'UserController@store')->name('super_admin.users.store');
    Route::get('/users/{user}/edit', 'UserController@edit')->name('super_admin.users.edit');
    Route::post('/users/{user}/edit', 'UserController@update')->name('super_admin.users.update');
    Route::get('/users/{user}/delete', 'UserController@delete')->name('super_admin.users.delete');

    // Plans
    Route::get('/plans', 'PlanController@index')->name('super_admin.plans');
    Route::get('/plans/create', 'PlanController@create')->name('super_admin.plans.create');
    Route::post('/plans/store', 'PlanController@store')->name('super_admin.plans.store');
    Route::get('/plans/{plan}/edit', 'PlanController@edit')->name('super_admin.plans.edit');
    Route::post('/plans/{plan}/edit', 'PlanController@update')->name('super_admin.plans.update');
    Route::get('/plans/{plan}/delete', 'PlanController@delete')->name('super_admin.plans.delete');

    // Subscriptions
    Route::get('/subscriptions', 'SubscriptionController@index')->name('super_admin.subscriptions');
    Route::get('/subscriptions/{subscription}/cancel', 'SubscriptionController@cancel')->name('super_admin.subscriptions.cancel');

    // Orders
    Route::get('/orders', 'OrderController@index')->name('super_admin.orders');

    // Settings
    Route::get('/settings/application', 'SettingController@application')->name('super_admin.settings.application');
    Route::post('/settings/application', 'SettingController@application_update')->name('super_admin.settings.application.update');

    Route::get('/settings/mail', 'SettingController@mail')->name('super_admin.settings.mail');
    Route::post('/settings/mail', 'SettingController@mail_update')->name('super_admin.settings.mail.update');

    Route::get('/settings/payment', 'SettingController@payment')->name('super_admin.settings.payment');
    Route::post('/settings/payment', 'SettingController@payment_update')->name('super_admin.settings.payment.update');

    Route::get('/settings/theme/{theme}', 'ThemeSettingController@edit')->name('super_admin.settings.theme');
    Route::post('/settings/theme/{theme}', 'ThemeSettingController@update')->name('super_admin.settings.theme.update');
    Route::get('/settings/theme/{theme}/activate', 'ThemeSettingController@activate')->name('super_admin.settings.theme.activate');
});

// Customer Portal Routes
Route::group(['namespace' => 'CustomerPortal', 'prefix' => '/portal/{customer}', 'middleware' => ['installed', 'customer_portal']], function () {
    // Dashboard
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('customer_portal.dashboard');

    // Invoices
    Route::get('/invoices', 'InvoiceController@index')->name('customer_portal.invoices');
    Route::get('/invoices/{invoice}', 'InvoiceController@show')->name('customer_portal.invoices.details');

    // PaypalExpress Checkout
    Route::post('/invoices/{invoice}/paypal/payment', 'Checkout\PaypalExpressController@payment')->name('customer_portal.invoices.paypal.payment');
    Route::get('/invoices/{invoice}/paypal/completed', 'Checkout\PaypalExpressController@completed')->name('customer_portal.invoices.paypal.completed');
    Route::get('/invoices/{invoice}/paypal/cancelled', 'Checkout\PaypalExpressController@cancelled')->name('customer_portal.invoices.paypal.cancelled');

    // Mollie Checkout
    Route::get('/invoices/{invoice}/mollie/payment', 'Checkout\MollieController@payment')->name('customer_portal.invoices.mollie.payment');
    Route::post('/invoices/{invoice}/mollie/webhook', 'Checkout\MollieController@webhook')->name('customer_portal.invoices.mollie.webhook');
    Route::get('/invoices/{invoice}/mollie/completed', 'Checkout\MollieController@completed')->name('customer_portal.invoices.mollie.completed');

    // Razorpay Checkout
    Route::get('/invoices/{invoice}/razorpay/checkout', 'Checkout\RazorpayController@checkout')->name('customer_portal.invoices.razorpay.checkout');
    Route::post('/invoices/{invoice}/razorpay/callback', 'Checkout\RazorpayController@callback')->name('customer_portal.invoices.razorpay.callback');

    // Stripe Checkout
    Route::get('/invoices/{invoice}/stripe/checkout', 'Checkout\StripeController@checkout')->name('customer_portal.invoices.stripe.checkout');
    Route::post('/invoices/{invoice}/stripe/payment', 'Checkout\StripeController@payment')->name('customer_portal.invoices.stripe.payment');
    Route::get('/invoices/{invoice}/stripe/completed', 'Checkout\StripeController@completed')->name('customer_portal.invoices.stripe.completed');

    // Estimates
    Route::get('/estimates', 'EstimateController@index')->name('customer_portal.estimates');
    Route::get('/estimates/{estimate}', 'EstimateController@show')->name('customer_portal.estimates.details');
    Route::get('/estimates/{estimate}/mark/{status?}', 'EstimateController@mark')->name('customer_portal.estimates.mark');

    // Payment
    Route::get('/payments', 'PaymentController@index')->name('customer_portal.payments');
    Route::get('/payments/{payment}', 'PaymentController@show')->name('customer_portal.payments.details');
});

// Application Routes
Route::group(['namespace' => 'Application', 'prefix' => '/{company_uid}', 'middleware' => ['installed', 'auth', 'dashboard']], function () {
    // Company Dashboard
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    // Customers
    Route::get('/customers', 'CustomerController@index')->name('customers');
    Route::get('/customers/create', 'CustomerController@create')->name('customers.create');
    Route::post('/customers/create', 'CustomerController@store')->name('customers.store');
    Route::post('/customer/store', 'CustomerController@customerstore')->name('customers.customer.store');
    Route::post('/customers/store', 'CustomerController@customerestimate')->name('customers.estimate.store');
    Route::get('/customers/{customer}/details', 'CustomerController@details')->name('customers.details');
    Route::get('/customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::post('/customers/{customer}/edit', 'CustomerController@update')->name('customers.update');
    Route::get('/customers/{customer}/delete', 'CustomerController@delete')->name('customers.delete');
    

    // Products & Services
    Route::get('/products', 'ProductController@index')->name('products'); 
    Route::get('/products/create', 'ProductController@create')->name('products.create');
    Route::post('/products/store', 'ProductController@store')->name('products.store');
    Route::post('/products/customer/store', 'ProductController@customerstore')->name('products.customer.store');
    Route::post('/products/estimate/store', 'ProductController@estimatestore')->name('products.estimate.store');
    Route::get('/products/{product}/edit', 'ProductController@edit')->name('products.edit');
    Route::post('/products/{product}/edit', 'ProductController@update')->name('products.update');
    Route::get('/products/{product}/delete', 'ProductController@delete')->name('products.delete');


     // Suppliers
     Route::get('/suppliers', 'SupplierController@index')->name('suppliers');
     Route::get('/suppliers/create', 'SupplierController@create')->name('suppliers.create');
     Route::post('/suppliers/create', 'SupplierController@store')->name('suppliers.store');
     Route::post('/suppliers/create/expense', 'SupplierController@expensestore')->name('suppliers.expense.store');
     Route::get('/suppliers/{supplier}/edit', 'SupplierController@edit')->name('suppliers.edit');
     Route::post('/suppliers/{supplier}/edit', 'SupplierController@update')->name('suppliers.update');
     Route::get('/suppliers/{supplier}/delete', 'SupplierController@delete')->name('suppliers.delete');

    // Invoices
    Route::get('/importExportView','InvoiceController@importExportView')->name('csv.view');
    Route::get('/export','InvoiceController@export')->name('export');
    Route::post('/import', 'InvoiceController@import')->name('import');
    Route::get('/invoices/export', 'InvoiceController@exportInvoice')->name('export.invoice');
    Route::get('/invoices/create', 'InvoiceController@create')->name('invoices.create');
    Route::post('/invoices/create', 'InvoiceController@store')->name('invoices.store');

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Plan extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'slug',
        'name',
        'description',
        'is_active',
        'price',
        'trial_period',
        'trial_interval',
        'invoice_period',
        'invoice_interval',
        'grace_period',
        'grace_interval',
        'prorate_day',
        'prorate_period',
        'prorate_extend_due',
        'active_subscribers_limit',
        'order',
    ];

    /**
     * Automatically cast attributes to given types
     * 
     * @var array
     */
    protected $casts = [
        'slug' => 'string',
        'is_active' => 'boolean',
        'price' => 'integer',
        'trial_period' => 'integer',
        'trial_interval' => 'string',
        'invoice_period' => 'integer',
        'invoice_interval' => 'string',
        'grace_period' => 'integer',
        'grace_interval' => 'string',
        'prorate_day' => 'integer',
        'prorate_period' => 'integer',
        'prorate_extend_due' => 'integer',
        'active_subscribers_limit' => 'integer',
        'deleted_at' => 'datetime',
        'order' => 'integer',
    ];

    /**
     * The plan may have many features.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function features(): HasMany
    {
        return $this->hasMany(PlanFeature::class, 'plan_id', 'id');
    }

    /**
     * The plan may have many subscriptions.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subscriptions(): HasMany
    {
        return $this->hasMany(PlanSubscription::class, 'plan_id', 'id');
    }

    /**
     * Create Plan Features
     *
     * @return void
     */
    public function addPlanFeatures($features): void
    {
        // Create new Plan Features
        foreach ($features as $feature => $value) {
            if ($feature === 'invoices_per_month' || $feature === 'estimates_per_month') {
                $this->features()->create(['slug' => $feature, 'value' => $value, 'resettable_period' => 1, 'resettable_interval' => 'month']);
            } else {
                $this->features()->create(['slug' => $feature, 'value' => $value]);
            }
        }
    }

    /**
     * Update Plan Features
     *
     * @return void
     */
    public function updatePlanFeatures($features): void
    {
        // Update new Plan Features
        foreach ($features as $feature => $value) {
            PlanFeature::where('plan_id', $this->id)->where('slug', $feature)->update(['value' => $value]);
        }
    }

    /**
     * Get Currency Attribute
     *
     * @return void
     */
    public function getCurrencyAttribute()
    {
        return get_system_setting('application_currency');
    }

    /**
     * Check if plan is free.
     *
     * @return bool
     */
    public function isFree(): bool
    {
        return (float) $this->price <= 0.00;
    }

    /**
     * Check if plan has trial.
     *
     * @return bool
     */
    public function hasTrial(): bool
    {
        return $this->trial_period && $this->trial_interval;
    }

    /**
     * Check if plan has grace.
     *
     * @return bool
     */
    public function hasGrace(): bool
    {
        return $this->grace_period && $this->grace_interval;
    }

    /**
     * Get plan feature by the given slug.
     *
     * @param string $featureSlug
     *
     * @return \App\Models\PlanFeature|null
     */
    public function getFeatureBySlug(string $featureSlug)
    {
        return $this->features()->where('slug', $featureSlug)->first();
    }

    /**
     * Activate the plan.
     *
     * @return $this
     */
    public function activate()
    {
        $this->update(['is_active' => true]);

        return $this;
    }

    /**
     * Deactivate the plan.
     *
     * @return $this
     */
    public function deactivate()
    {
        $this->update(['is_active' => false]);

        return $this;
    }

    /**
     * List Plans for Select2 Javascript Library
     * 
     * @return collect
     */
    public static function getSelect2Array() {        
        $response = collect();
        foreach(self::all() as $plan){
            $response->push([
                'id' => $plan->id,
                'text' => $plan->name
            ]);
        }
        return $response;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Method\RoleMethod;
use App\Models\Method\UserMethod;
use App\Traits\CompanyUserTrait;
use App\Traits\HasAddresses;
use Laravel\Passport\HasApiTokens;
use App\Traits\ApiTokens;
use App\Traits\UUIDTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable 
{ 
    use Notifiable, HasRoles,UserMethod;
    use UUIDTrait;
    use HasAddresses;
    use HasApiTokens;
    use CompanyUserTrait;
    use UserMethod;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 
        'first_name',
        'last_name',
        'state_id',
        'email',
        'email_verified_at',
        'password',
        'telephone',
        'provider',
        'provider_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

     /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
 
    /**
     * Define Relation with UserSetting Model
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function settings()
    {
        return $this->hasMany(UserSetting::class);
    }

    public function company()
    {
        return $this->hasOne(Company::class,'id','owner_id');
    }

    /**
     * Get User Specified setting
     *
     * @param string $key
     * 
     * @return mixed
     */
    public function getSetting($key)
    {
        return UserSetting::getSetting($key, $this->id);
    }

    /**
     * Set User Specified setting
     *
     * @param string $key
     * @param string $value
     * 
     * @return void
     */
    public function setSetting($key, $value)
    {
        return UserSetting::setSetting($key, $value, $this->id);
    }

    /**
     * Get Full Name Attribute
     * 
     * @return string
     */
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Return Default User Avatar Url
     * 
     * @return string (url)
     */
    public function getDefaultAvatar()
    {
        return asset('assets/images/avatar/user.png');
    }

    /**
     * Get User's Avatar Url || Default Avatar
     * 
     * @return string (url)
     */
    public function getAvatarAttribute()
    {
        $avatar = $this->getSetting('avatar');
        return $avatar ? asset($avatar) : $this->getDefaultAvatar();
    }
}

resources/views/super_admin/orders/_table.blade.php
{{-- @if($orders->count() > 0)
    <div class="table-responsive">
        <table class="table mb-0 thead-border-top-0 table-striped">
            <thead>
                <tr>
                    <th class="w-30px" class="text-center">{{ __('messages.order_id') }}</th>
                    <th>{{ __('messages.transaction_id') }}</th>
                    <th>{{ __('messages.user') }}</th>
                    <th>{{ __('messages.plan') }}</th>
                    <th>{{ __('messages.price') }}</th>
                    <th>{{ __('messages.payment_type') }}</th>
                    <th>{{ __('messages.created_at') }}</th>
                </tr> 
            </thead> 
            <tbody class="list" id="orders">
                @foreach ($orders as $order)
                    <tr>
                        <td>
                            <p class="mb-0">{{ $order->order_id }}</p>
                        </td>
                        <td>
                            <p class="mb-0">{{ $order->transaction_id }}</p>
                        </td>
                        <td>
                            @if($order->company)
                                <a class="mb-0" href="{{ route('super_admin.users.edit', $order->company->owner->id) }}">{{ $order->company->owner->full_name }}</a>
                            @else
                                <a class="mb-0">-</a>
                            @endif
                        </td>
                        <td>
                            @if($order->plan)
                                <a class="mb-0" href="{{ route('super_admin.plans.edit', $order->plan->id) }}">{{ $order->plan->name ?? '-' }}</a>
                            @else
                                <a class="mb-0">-</a>
                            @endif
                        </td>
                        <td>
                            <p class="mb-0">{!! money($order->price, $order->currency) !!}</p>
                        </td>
                        <td>
                            {{ $order->payment_type }} 
                        </td>
                        <td class="text-center"><i class="material-icons icon-16pt text-muted-light mr-1">today</i> {{ $order->created_at->format('Y-m-d') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @if(method_exists($orders, 'links'))
        <div class="row card-body pagination-light justify-content-center text-center">
            {{ $orders->links() }}
        </div>
    @endif
@else
    <div class="row justify-content-center card-body pb-0 pt-5">
        <i class="material-icons fs-64px">account_box</i>
    </div>
    <div class="row justify-content-center card-body pb-5">
        <p class="h4">{{ __('messages.no_orders_yet') }}</p>
    </div>
@endif --}}

<!-- Basic Tables start -->
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ __('messages.orders') }}</h4>
                {{-- <a href="{{ route('super_admin.users.create') }}" class="btn btn-success ml-3 float-right"><i class="material-icons"></i> {{ __('messages.add_user') }}</a> --}}
            </div>
            @if($orders->count() > 0)
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>{{ __('messages.order_id') }}</th>
                                <th>{{ __('messages.transaction_id') }}</th>
                                <th>{{ __('messages.user') }}</th>
                                <th>{{ __('messages.plan') }}</th>
                                <th>{{ __('messages.price') }}</th>
                                <th>{{ __('messages.payment_type') }}</th>
                                <th>{{ __('messages.created_at') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($orders as $order)
                                <tr>
                                    <td>
                                        {{ $order->order_id }}
                                    </td>
                                    <td>{{ $order->transaction_id }}</td>
                                    <td>
                                        @if($order->company)
                                            <a class="mb-0" href="{{ route('super_admin.users.edit', $order->company->owner->id) }}">{{ $order->company->owner->full_name }}</a>
                                        @else
                                            <a class="mb-0">-</a>
                                        @endif
                                    </td>
                                    <td>
                                        @if($order->plan)
                                            <a class="mb-0" href="{{ route('super_admin.plans.edit', $order->plan->id) }}">{{ $order->plan->name ?? '-' }}</a>
                                        @else
                                            <a class="mb-0">-</a>
                                        @endif
                                    </td>
                                    <td>
                                        {!! money($order->price, $order->currency) !!}
                                    </td>
                                    <td>
                                        {{ $order->payment_type }} 
                                    </td>
                                    <td><i class="material-icons icon-16pt text-muted-light mr-1">today</i>
                                        {{ $order->created_at->format('Y-m-d') }}</td>
                                </tr>
                                @endforeach
                        </tbody>
                    </table>
                </div>
                @if(method_exists($orders, 'links'))
                <div class="row card-body pagination-light justify-content-center text-center">
                    {{ $orders->links() }}
                </div>
            @endif
        @else
            <div class="row justify-content-center card-body pb-0 pt-5">
                <i class="material-icons fs-64px"></i>
            </div>
            <div class="row justify-content-center card-body pb-5">
                <p class="h4">{{ __('messages.no_orders_yet') }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
<!-- Basic Tables end -->
@section('page_head_scripts')
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/app-assets/vendors/css/vendors.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/vendors/css/tables/datatable/rowGroup.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css') }}">
    <!-- END: Vendor CSS-->
    <link rel="stylesheet" type="text/css"
    href="{{ asset('theme/app-assets/css/core/menu/menu-types/vertical-menu.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('theme/app-assets/css/plugins/charts/chart-apex.css') }}">
<link rel="stylesheet" type="text/css"
    href="{{ asset('theme/app-assets/css/plugins/extensions/ext-component-toastr.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('theme/app-assets/css/pages/app-invoice-list.css') }}">
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css"
        href="{{ asset('theme/app-assets/css/core/menu/menu-types/vertical-menu.css') }}">
    <!-- END: Page CSS-->
@endsection

@section('page_body_scripts')
    <!-- BEGIN: Page JS-->
    <script src="{{ asset('theme/app-assets/js/scripts/pages/dashboard-ecommerce.js') }}"></script>
    <!-- END: Page JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/jszip.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/vfs_fonts.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/tables/datatable/dataTables.rowGroup.min.js') }}"></script>
    <script src="{{ asset('theme/app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js') }}"></script>
    <!-- END: Page Vendor JS-->
    <script src="{{ asset('assets/js/settings.js') }}"></script>
    <script src="{{ asset('assets/vendor/Chart.min.js') }}"></script>
    <script src="{{ asset('assets/js/chartjs-rounded-bar.js') }}"></script>
    <script src="{{ asset('assets/js/charts.js') }}"></script>
    <!-- BEGIN: Page JS-->
    <script src="{{ asset('theme/app-assets/js/scripts/pages/dashboard-analytics.js') }}"></script>
    <script src="{{ asset('theme/app-assets/js/scripts/pages/app-invoice-list.js') }}"></script>
    <script src="{{ asset('theme/app-assets/js/scripts/cards/card-analytics.js') }}"></script>
    <script src="{{ asset('theme/app-assets/js/scripts/cards/card-statistics.js') }}"></script>
@endsection

resources/views/super_admin/orders/index.blade.php
@extends('layouts.app', ['page' => 'super_admin.orders'])

@section('title', __('messages.orders'))
    
@section('page_header')
    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ __('messages.orders') }}</li>
                </ol>
            </nav>
            <h1 class="m-0">{{ __('messages.orders') }}</h1>
        </div>
    </div>
@endsection

@section('content')
    <div class="card">
        @include('super_admin.orders._table')
    </div>
@endsection